### PR TITLE
fix #60 - Kauth Action Timeout

### LINKED ISSUE #60: [KCModule: msm_kernel] - problems when downloading packages
There is a problem when the kernel installation take too much time (ex: having do download packages)
the action dialog say that the job is done, but it's not really finished, pacman is still running in background. 

screenshot_20160427_154741

I investigated. and I don't understand the problem.
in
`ActionDialog::startJob()`
the function
`if ( job->exec() )` who start the KAuth action
 return false before the pacman process exit in

> ActionReply
> KernelAuthHelper::runPacman( const QVariantMap& args )
> {
>     .....
>     .....
>     ...
>     pacman->waitForFinished( -1 );
>     return actionReply;
> 
> }

Here my debug output (i added qDebug outputs)

```
"16:15:04"  before 'if ( job->exec() )'
Debug message from helper: "16:15:10"  before 'pacman->start( "/usr/bin/pacman", args["arguments"].toStringList() );'
"16:15:29"  after 'if ( job->exec() )'
Debug message from helper: "16:15:50"  after 'pacman->waitForFinished( -1 );'
```

we can see that job-exec() returned 20s before pacman QProcess finished
maybe someone will understand why. I don't.

best regards

### PR DESCRIPTION
**Pull request by scachemaille**
Add maximum timeout for each KauthAction

## # REMARKS
it need at least Kauth V5.29.0
I'm not sure if and how to put a constraint in makefile for this.

### CODE REVIEW

**Comment by Kirek** [comment]
Nice, but only kernel, language_packages and mhwd need a big timeout, all other calls should be instant or almost instant (because if not something has really gone wrong), so the default timeout is already okay.

**Comment by scachemaille** [comment]
would you I revert back other action? or change to maybe one minutes? I was thinking that maybe locale needed too. as the locale gen can take some times on a slow computer. 
And do you know how to constrain the build with KF5 min to 5.29?

**Comment by Kirek** [comment]
Yes, for locale one minute timeout would be fine too.
To put a constrain for KF5 5.29, you should modify the cmakelists file in the root, add `set(KF5_MIN_VERSION "5.29")` and then change change the find_package line like this `find_package(KF5 ${KF5_MIN_VERSION} REQUIRED COMPONENTS`

**Comment by scachemaille** [comment]
reverted all short action timeout to default.
changed timeout for locale module to 1min
added the KF5 min version to 5.29.

Build fine one unstable.
and doesn't build on stable with buildpkg because of the KF5 constraint.
I tried to install a kernel and it worked as expected.
all seems good.

**Comment by Kirek** [comment]
Looks good!

**Pull request merged**
