### PR TITLE
Change default settings for MSN

### PR DESCRIPTION
**Pull request by Ste74**
Hi @Kirek , @philmmanjaro do you think to change this default settings ?
see this [video](https://youtu.be/QLETVR07uU8?t=8m)
Do you think or expalin what you mean with new kernel reccomended .. also because we ship the Isos with  LTS kernel we ( with this modify )

### CODE REVIEW

**Comment by scachemaille** [comment]
why to not check for unsupported kernel? it tell user that he run or as an unsupported kernel and that it should uninstall it or install a new kernel.

**Comment by oberon2007** [comment]
I also see it like this that it would be good to notify by default only for LTS, not for latest kernels. But are the settings in the PR really correct?

**Comment by Ste74** [comment]
Set new kernel LTS true , kernel not supported true and raccomended false .. no ?

**Comment by jonathonf** [comment]
This change makes sense to me - there's no need to notify the majority of users that there's an -rc kernel available, however it does make sense to notify if the running kernel is unsupported (for those who manually install a new kernel series), and that there's a new LTS available (for users who don't install a new kernel series).

This might be combined with a [`linux-lts` metapackage](https://forum.manjaro.org/t/idea-kernel-metapackages-renaming/23037/53?u=jonathon) to move LTS kernel users from old to new LTS kernel.

**Comment by Ste74** [comment]
Thank you :) ... fun, I realized now this : don't finish the phrase :p

**Pull request merged**
