### PR TITLE
Notification settings in only 1 place

### PR DESCRIPTION
**Pull request by scachemaille**
I removed the notifications settings tabs from the different place (kernel, and language) as they were not implemented (at least the kernel notification tab in kernel from manjaro-settings-manager).

so now. there is only the notifications page in manjaro-settings-manager and a KCM module for the KDE version.

I find like that more coherent. you may not agree with me.
_**Rest to solve the problem of settings file path for the no KDE user. see #65**_
### TODO
Need to modify the PKGBUILD to include the new KCM module in manjaro-settings-manager-kcm
and to not include it in the other package.
### EDIT
I checked the PKGBUILD don't need to be adapted.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@Kirek: please check and update the **PKGBUILD** accordently.

**Comment by scachemaille** [comment]
One file is missing. 
I close this one and will create a new one with the missing file
:wink:

**Comment by philmmanjaro** [comment]
Well you could have committed to your branch and all changes will be added to this one ...

**Comment by scachemaille** [comment]
euh.. 
I'm not sure to understand. I'm still not an expert with git. more used with svn

**Comment by philmmanjaro** [comment]
@scachemaille: check for example https://github.com/manjaro/packages-community/pull/165. Simply commit to your branch and it will adopt here.

**Comment by philmmanjaro** [comment]
**fix missing files for the notifications commit** is now the latest current commit from your end. Like magic ;)

**Comment by scachemaille** [comment]
oooh.. if I understand the pull request point to the head of my master branch?
if so.. it's not good I commit things before the merge is accepter and done.. right?

**Comment by philmmanjaro** [comment]
For now yes. It will pull whatever you push to your master. To understand your work. To which package should now the notifier go? Do we have now two notifiers? Which are their binary file names now?

**Comment by philmmanjaro** [comment]
Normally you make a branch on your own fork. Example **notifier-mod**. Commit to that your changes and create a pull-request from it. That is how it is normally done ...

**Comment by scachemaille** [comment]
ok I got it. 
about this pull request.
it's just like as say the title, it's to have the settings of the notifier in only form, for it's own. and still in **msm-settings.manager**.

for the 2 notifiers it's still not committed.

**Comment by philmmanjaro** [comment]
Ok. I got it now. I assume you have already tested it and didn't add any regression with your patch. Lets see @Kirek's feedback on this. From flying over it, it seems to be fine.

**Comment by scachemaille** [comment]
yeah I tested it. and like as I saw on XFCE the notifications change don't have any effect due to the implementation of doing it in manjaro-settings-manager who is running as root.
so yes my modifications don't add any regression, but also don't resolve the problems. 
see #65

**Comment by Kirek** [comment]
The notifications in one place in kcm is how it was done originally, but I put in they respective kcm modules because that made it appear 2 "Notificanion" icon in the kde systemsettings. 
Not that the current design is any good either, so I will merge this.

About the problems with msm running at root is another bug that slipped through when I merged the old msm with the kcm modules. We solved this in the old daemon like that:
https://github.com/manjaro/manjaro-settings-manager/blob/0.4.x/src/manjaro-settings-manager-daemon/daemon.cpp#L283

**Comment by scachemaille** [comment]
I will fix the settings root problems in msm-settings-manager

**Pull request merged**
