### PR TITLE
additional controls to change the rate and delay of keystrokes in keyboard module

### PR DESCRIPTION
**Pull request by georoot**
I noticed that current settings manager did not provide controls to change the typing rate and set delay for keystrokes unlike what i found in mint (screenshot for mint 
keyboard
) This patch takes care of this issue. Although the UI might need some tweeks.

### CODE REVIEW

**Comment by Kirek** [comment]
Did you test if this values persist after reboot?

**Comment by georoot** [comment]
I did not check in this explicitly. But i am using xset to set the values. I don't think there is going to be any problem with reboot still let me confirm that for you .

**Comment by georoot** [comment]
No the values are not persisting. I am sure there should be a simple fix. Let me search and apply that on.

**Comment by georoot** [comment]
i tried to add a script to /etc/rc.local but it seems like it needs sudo priveledges for that. There seems to be no other method for xset to have the same values even after reboot except adding it to the startup script. Any ideas on which script can i used for this ? . i already used in in .xinitrc and that one does seem to work well for me.

**Comment by Kirek** [comment]
.xinitrc will be a good place to put it

**Comment by georoot** [comment]
@Kirek i added the content into the xinitrc file and pushed the changes. Please review them

**Comment by Kirek** [comment]
This code will always append the command at the end of the file every time, it should check if already existst a line that starts with "exec xset r rate " and substitute that.

**Comment by georoot** [comment]
@Kirek please check it now. It is tested and seems to be working fine. One issue though insted of using QFile i prefered to use File in c++ as i was more comfortable with that.

**Pull request merged**
