### PR TITLE
force to use gtk theme

### PR DESCRIPTION
**Pull request by vejobuj**

### CODE REVIEW

**Comment by Kirek** [comment]
MSM is used by kde and lxqt so this will break their theme.

**Comment by vejobuj** [comment]
But at the moment it does not match the current style of an Xfce session and not even of KDE.
And as you know, the more annoyed with it are Xfce users - for evidence the download statistics. http://sourceforge.net/projects/manjarolinux/files/release/0.8.12/
What we could do is change this there and create a second Launcher with the variable NotShowIn = XFCE;GNOME;

**Comment by Kirek** [comment]
Two launchers would be a good option

**Comment by vejobuj** [comment]
Done :)

**Comment by Kirek** [comment]
Nice, merged.

**Pull request merged**
