### PR TITLE
Added slovak translation of menu items and its comments

### PR DESCRIPTION
**Pull request by prescott66**
I have added slovak translation of menu items for manjaro settings manager and notifier settings. Also translated comments for it.

### CODE REVIEW

**Comment by scachemaille** [comment]
@prescott66  could you also translate msm_kde_notifier_settings please?

**Comment by prescott66** [comment]
of course.i will create new pull request later.i am not good friend with guthub and git x-D

**Comment by scachemaille** [comment]
if you commit change in your branch they will appear in this request

**Comment by prescott66** [comment]
i think it is done :-)

**Pull request merged**
