### PR TITLE
Ux improvement

### PR DESCRIPTION
**Pull request by sanchitsamuel**
**_Changelog_**

1. Installation dialog now has a show/hide details option, details are hidden by default.
2. Installation dialog UI improved for better user experience.
3. Cursor loading is showing while loading any settings module.
4. Big buttons in hardware made small and look like hyper-links 

**_Screenshots_**
screenshot_20170522_161230

### CODE REVIEW

**Comment by oberon2007** [comment]
Very nice! Just tested this and I like it 👍
Seems to work flawlessly.
I've built -dev packages and will push them if anyone wants to try...

**Comment by oberon2007** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170522/011398.html

**Comment by sanchitsamuel** [comment]
I'll still improve a few things, with hardware module. Do i need to create a pull request for that as well?

**Comment by oberon2007** [comment]
I'm not convinced that hard-coded colors for the buttons are a good idea - especially blue?? 😉

**Comment by sanchitsamuel** [comment]
I wanted it to look like a hyper link, bt it doesn't work. 2 big buttons are a lil wired to look at. 
What should we do leave it as is?

**Comment by philmmanjaro** [comment]
What other options do we have there?

**Comment by sanchitsamuel** [comment]
I can replace the buttons with the ClickableLabel which I added in the installation dialog. If that makes it look good. 
Else
If you guys want I'll undo to old 2 buttons side by side.

**Comment by philmmanjaro** [comment]
@sanchitsamuel: can you add some screenshots of both variants? I also assume you're talking about the QT menu we use for MSM in DEs other than KDE and not the KDE settings integration.

**Comment by sanchitsamuel** [comment]
I cannot put some screenshots rite now, will do it later at night. 
Also ClickAbleLabel is a sub-class of QLable the source is added in the repo itself in the dir 'libmsm'

**Comment by philmmanjaro** [comment]
Since @Kirek has to review it anyway - no pressure. We will see on how we get the best out of it. Thx so far for your effort.

**Comment by Kirek** [comment]
Nice changes, looks good.

ClickableLabel class can be completely avoided and use QLabel with hyperlinks:

In ActionDialog contructor
```
    m_showDetails = new QLabel();
    vBoxLayout->addWidget( m_showDetails );
    m_showDetails->setTextFormat( Qt::RichText );
    m_showDetails->setTextInteractionFlags( Qt::TextBrowserInteraction );
    ClickableLabel::connect( m_showDetails, &QLabel::linkActivated,
                             this, &ActionDialog::showDetails );
    this->showDetails( "#hide" );
```
And change the function too
```
void
ActionDialog::showDetails( const QString& link )
{
    if ( link == "#hide" )
    {
        m_terminal -> hide();
        m_showDetails->setText( "<a href=\"#show\">" + tr( "Show Details" ) + "</a>" );
        m_informationLabel->show();
        window()->setFixedSize( x, y );
        this->resize( x, y );
    }
    else if ( link == "#show" )
    {
        m_terminal -> show();
        m_showDetails->setText( "<a href=\"#hide\">" + tr( "Hide Details" ) + "</a>" );
        m_informationLabel->hide();
        window()->setFixedSize( x, y + 100 );
        this->resize( x, y + 100 );
    }
}
```

This way we can event remove m_DetailsOn variable.

Also instead of storing the size of the widget in `x` and `y`, you can just use `this->height()` and `this->width()`

The change with the button of the hardware module are okay too, but i would remove the line "You can also:"

**Comment by sanchitsamuel** [comment]
Ok @Kirek I'll fix these things by tomorrow.
Thanks for the feedback. 
@philmmanjaro 
Here are the screenshots:
Old
screenshot_20170527_210555

New
screenshot_20170527_210522

**Comment by sanchitsamuel** [comment]
```
    QLabel::connect( m_showDetails, &QLabel::linkActivated,
                             this, &ActionDialog::showDetails );
```
@Kirek I used this but the 'slot'(show details) does not get called.

**Comment by Kirek** [comment]
Did you put a html link in the QLabel? `m_showDetails->setText( "<a href=\"#show\">" + tr( "Show Details" ) + "</a>" );`
And showDetails function should accept a string as the first variable 
`ActionDialog::showDetails( const QString& link )`

**Comment by sanchitsamuel** [comment]
yep have made those changes already.

**Comment by Kirek** [comment]
This are the changes that are made to make it work:
[msm-ux-qlabel.txt](https://github.com/manjaro/manjaro-settings-manager/files/1033934/msm-ux-qlabel.txt)

**Comment by philmmanjaro** [comment]
Looking good so far. When we put all together we may spin another development package for a bigger review. @sanchitsamuel: you seem to be a good addition to our team :smile:

**Comment by sanchitsamuel** [comment]
@Kirek done, there was a small mistake in my code, its working now.
@philmmanjaro its my pleasure to help you guys. Manjaro has always be great for me, its my time to give back. :)

**Comment by Tids** [comment]
I really like the new install dialog-window :D

My main critic right now is with the "Auto Install OpenSource/Propietary Driver" in generall. Because this will only install graphicsdrivers, while msm also handles networking drivers. So this might be confusing, because it's above everything.

-----
Jjust to ask - would something like this be possible?
rect5529

**Comment by sanchitsamuel** [comment]
@Tids 
How did you make the UI (screenshot)?
Its possible. I have issues with MHWD module as well, have been doing some brain storming to improve the UX around it.

**Comment by Tids** [comment]
@sanchitsamuel
It's been made in inkscape as vector graphics. The inspiration was the networkmanager module of KDE Plasma. I can attach them if they would help you.

But yeah it's hard to find a good looking, usable interface for it 😅

**Comment by sanchitsamuel** [comment]
ok, cool thanks for the idea. 
I'll try it out. 
Lets see whats the out come.

**Comment by Tids** [comment]
[Manjaro Hardware Detection user Interface.zip](https://github.com/manjaro/manjaro-settings-manager/files/1047418/Manjaro.Hardware.Detection.user.Interface.zip)
^ here is the vectorgraphics. In case its usefull in some way.

**Comment by sanchitsamuel** [comment]
I'm planning to stick with the tree view* with more info on the right side (tree view can be visualised as the device manager on Win**ws but there you have to double click for more info here you'll get more info on the device you click on. Also the reason to stick with tree view is because I don't know how to make the KDE like view :p

*For QT people tree view here mean tree widget

**Comment by philmmanjaro** [comment]
@sanchitsamuel: seems [some people](https://forum.manjaro.org/t/25895/10) don't like the new links in the widget and want the buttons back :smile:

**Comment by sanchitsamuel** [comment]
@philmmanjaro Sorry for late reply, I didn't get any notification for this.
I'm not entirely happy with the change myself. 
We should revert to buttons for now, before we can think of something better.
I want to peruse with @Tids idea but I'm not able to make enough time for it right now.

**Comment by philmmanjaro** [comment]
@sanchitsamuel: I recommend that too. Can you do the needed changes and I'll merge it?

**Comment by sanchitsamuel** [comment]
Yep I'll do it give me some time.

**Comment by sanchitsamuel** [comment]
@philmmanjaro #109

**Comment by philmmanjaro** [comment]
@sanchitsamuel: it has conflicts. Can you merge **master** first and rebase?

**Comment by sanchitsamuel** [comment]
@philmmanjaro done

**Comment by philmmanjaro** [comment]
Gives me still an error ...

```
[ 81%] Building CXX object src/modules/mhwd/CMakeFiles/msm_page_mhwd.dir/msm_page_mhwd_autogen/moc_compilation.cpp.o
/build/manjaro-settings-manager/src/manjaro-settings-manager-d197aaef83964d4de184676bc01d0ad19758c6ce/src/modules/mhwd/MhwdModule.cpp: In constructor 'MhwdModule::MhwdModule(QWidget*, const QVariantList&)':
/build/manjaro-settings-manager/src/manjaro-settings-manager-d197aaef83964d4de184676bc01d0ad19758c6ce/src/modules/mhwd/MhwdModule.cpp:74:38: error: 'QLabel' has not been declared
     connect( ui->buttonInstallFree, &QLabel::linkActivated,
                                      ^~~~~~
/build/manjaro-settings-manager/src/manjaro-settings-manager-d197aaef83964d4de184676bc01d0ad19758c6ce/src/modules/mhwd/MhwdModule.cpp:81:41: error: 'QLabel' has not been declared
     connect( ui->buttonInstallNonFree, &QLabel::linkActivated,
                                         ^~~~~~
```

**Comment by sanchitsamuel** [comment]
`connect( ui->buttonInstallFree, &QPushButton::clicked,
             [=] ( )
    {
        MhwdCommon::installFreeConfiguration();
        load();
    } );
    connect( ui->buttonInstallNonFree, &QPushButton::clicked,
             [=] ( )
    {
        MhwdCommon::installNonFreeConfiguration();
        load();
    } );`


I changed it to `QPushButton` on the ux_improvement branch.

**Comment by philmmanjaro** [comment]
Well, more got changed in **master**. So I had to do this also: https://github.com/manjaro/manjaro-settings-manager/commit/8dd52f5d1fefb99a7effaa2732b4d2c0641ce080

**Comment by sanchitsamuel** [comment]
ok, is it working now?

**Comment by philmmanjaro** [comment]
Looks like it.

**Pull request merged**
